### ISSUE TITLE
Python errors when downloading schedule

### ISSUE THREAD

**Issue by jaywink** [delijati/fosdem-qml#1]
Awesome to get something like this, just in time! :dancer: 

Anyway, just downloaded from the store, version 0.2.2. My phone is Bq Aquaris E4.5, running rc-proposed, updated a few days ago (so basically very close to OTA-9 stuff).

I get this error after accepting the pop-up xml url dialog, which seems to be correct (https://fosdem.org/2016/schedule/xml).

![screenshot20160125_214305517](https://cloud.githubusercontent.com/assets/1174866/12562341/4e9ae93e-c3ad-11e5-8daf-0101a7ee783f.png)

My network does work. Anything I can do to help debug, assuming this does not happen to you? I'm happy to drop in the terminal etc.

**Comment by delijati** [comment]
Hi jaywink, could you verify if the dirctory (path) exists. I will test it later with my bq.

**Comment by delijati** [comment]
Hi jaywink, could you verify if the dirctory (path) exists. I will test it later with my bq.

**Comment by jaywink** [comment]
It didn't exist, I created it manually and now the app works. Works great, thanks again, this will make my life easier this weekend ;)

So the installation or download should make sure the folder is created to fix this bug.

**Comment by delijati** [comment]
Fixed this issue and added some more features "starred" :)
